project:
  type: website

website:
  title: "University Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Clarkson/clarkson_university.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



