project:
  type: website

website:
  title: "University Notes"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Clarkson/clarkson_university.qmd
    logo: graduation_cap.jpg

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    smooth-scroll: true
