project:
  type: website

website:
  title: "Will You Be My Valetine?"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
    logo: istockphoto-1903985199-612x612.jpg

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    smooth-scroll: true
